### ISSUE TITLE
TypeError Cannot read property 'engine_version' of undefined

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#155]
Try accessing this measurement to reproduce: http://explorer-beta.ooni.io/measurement/c55MMtTAdZMTa93Jt9nnXvh44s0Gqv09Pu6oi8cRZZvFo3seJVw2x8QCpPJfGZ24?input=http://www.tudehpartyiran.org

```
{ TypeError: Cannot read property 'engine_version' of undefined
    at CommonDetails (components/measurement/CommonDetails.js:55:6)
    at d (/usr/src/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:28:492)
    at ua (/usr/src/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:30:494)
    at a.render (/usr/src/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:35:48)
    at a.read (/usr/src/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:34:288)
    at renderToString (/usr/src/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:45:6)
    at renderPage (/usr/src/app/node_modules/next/dist/server/render.js:277:26)
    at Function.getInitialProps (pages/_document.js:8:17)
    at _callee$ (/usr/src/app/node_modules/next/dist/lib/utils.js:111:30)
    at tryCatch (/usr/src/app/node_modules/regenerator-runtime/runtime.js:62:40) sourceMapsApplied: true }
```

**Comment by sarathms** [comment]
This seems to affect measurements for legacy tests. In this case, `http_requests`. Two of the ways to handle this:
1) We skip the row from the table where the value isn't available. We already do this where `engine_version` (OONI Probe Version) isn't available (from legacy probes, but for all tests).
![image](https://user-images.githubusercontent.com/700829/57540363-905f0100-731a-11e9-82a1-de7a1ed66e89.png)
![image](https://user-images.githubusercontent.com/700829/57540400-a40a6780-731a-11e9-9d59-63ef97d52a91.png)

2) We make it explicit by keeping the row and put up a message that sounds like "_information not available for this measurement_"
