### ISSUE TITLE
500 error when accessing measurements with missing test_keys->queries

### ISSUE THREAD

**Issue by anadahz** [ooni/explorer#358]
http://explorer.ooni.org/measurement/20190208T205844Z_AS8151_W9nWn2htXTMopfAZhMDuD5BebiDFOykWywcOrH7J7J4zOe9mDc?input=http://199.58.81.140/tor/status-vote/current/consensus.z

http://explorer.ooni.org/measurement/20190208T201519Z_AS8151_DfGKQsHuCJLis744rHL0TDTB0SxehjjPbu6YZZSv0vRgQQSASz?input=http://199.58.81.140/tor/status-vote/current/consensus.z

**Comment by hellais** [comment]
@sarathms I was able to reproduce this locally.

The stack trace of the exception is the following:

```
TypeError: Cannot read property 'map' of undefined
    at WebConnectivityDetails (/Users/x/code/ooni/explorer/.next/server/static/development/pages/measurement.js:4970:18)
    at processChild (/Users/x/code/ooni/explorer/node_modules/react-dom/cjs/react-dom-server.node.development.js:2888:14)
    at resolve (/Users/x/code/ooni/explorer/node_modules/react-dom/cjs/react-dom-server.node.development.js:2812:5)
    at ReactDOMServerRenderer.render (/Users/x/code/ooni/explorer/node_modules/react-dom/cjs/react-dom-server.node.development.js:3202:22)
    at ReactDOMServerRenderer.read (/Users/x/code/ooni/explorer/node_modules/react-dom/cjs/react-dom-server.node.development.js:3161:29)
    at renderToString (/Users/x/code/ooni/explorer/node_modules/react-dom/cjs/react-dom-server.node.development.js:3646:27)
    at render (/Users/x/code/ooni/explorer/node_modules/next-server/dist/server/render.js:86:16)
    at renderPage (/Users/x/code/ooni/explorer/node_modules/next-server/dist/server/render.js:211:20)
    at Function.getInitialProps (/Users/x/code/ooni/explorer/.next/server/static/development/pages/_document.js:2682:18)
    at Object.loadGetInitialProps (/Users/x/code/ooni/explorer/node_modules/next-server/dist/lib/utils.js:42:35)
    at Object.renderToHTML (/Users/x/code/ooni/explorer/node_modules/next-server/dist/server/render.js:218:36)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
TypeError: Cannot read property 'map' of undefined
    at WebConnectivityDetails (/Users/x/code/ooni/explorer/.next/server/static/development/pages/measurement.js:4970:18)
    at processChild (/Users/x/code/ooni/explorer/node_modules/react-dom/cjs/react-dom-server.node.development.js:2888:14)
    at resolve (/Users/x/code/ooni/explorer/node_modules/react-dom/cjs/react-dom-server.node.development.js:2812:5)
    at ReactDOMServerRenderer.render (/Users/x/code/ooni/explorer/node_modules/react-dom/cjs/react-dom-server.node.development.js:3202:22)
    at ReactDOMServerRenderer.read (/Users/x/code/ooni/explorer/node_modules/react-dom/cjs/react-dom-server.node.development.js:3161:29)
    at renderToString (/Users/x/code/ooni/explorer/node_modules/react-dom/cjs/react-dom-server.node.development.js:3646:27)
    at render (/Users/x/code/ooni/explorer/node_modules/next-server/dist/server/render.js:86:16)
    at renderPage (/Users/x/code/ooni/explorer/node_modules/next-server/dist/server/render.js:211:20)
    at Function.getInitialProps (/Users/x/code/ooni/explorer/.next/server/static/development/pages/_document.js:2682:18)
    at Object.loadGetInitialProps (/Users/x/code/ooni/explorer/node_modules/next-server/dist/lib/utils.js:42:35)
    at Object.renderToHTML (/Users/x/code/ooni/explorer/node_modules/next-server/dist/server/render.js:218:36)
```
